# Generated by Django 4.2.10 on 2024-03-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_details',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='account_details',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
    ]
